### Introducción a Numpy

In [3]:
import numpy as np

In [4]:
valoraciones = np.array([[8, 7, 8, 5], [2, 6, 2, 1], [8, 8, 9, 5]])
valoraciones

array([[8, 7, 8, 5],
       [2, 6, 2, 1],
       [8, 8, 9, 5]])

In [5]:
# Acceder a la información
valoraciones[0][1]

7

In [6]:
# Notacion alternativa para acceder a la misma información
valoraciones[0, 1]

7

In [9]:
# Arreglo de tres dimensiones
valoraciones_2 = np.array([[[8, 7, 8, 5], [2, 5, 5, 2]], [[2, 6, 8, 4], [8, 9, 7, 4]], [[8, 8, 9, 3], [10, 9, 10, 8]]])

In [10]:
valoraciones_2

array([[[ 8,  7,  8,  5],
        [ 2,  5,  5,  2]],

       [[ 2,  6,  8,  4],
        [ 8,  9,  7,  4]],

       [[ 8,  8,  9,  3],
        [10,  9, 10,  8]]])

In [11]:
valoraciones_2[0]

array([[8, 7, 8, 5],
       [2, 5, 5, 2]])

In [12]:
valoraciones_2[0, 0]

array([8, 7, 8, 5])

In [13]:
valoraciones_2[0, 0, 0]

8

In [14]:
# Arrays vacios
np.zeros((3, 2, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [16]:
# Operaciones entre arrays de los mismos tamaños
valoraciones_2 + np.ones((3, 2, 4))

array([[[ 9.,  8.,  9.,  6.],
        [ 3.,  6.,  6.,  3.]],

       [[ 3.,  7.,  9.,  5.],
        [ 9., 10.,  8.,  5.]],

       [[ 9.,  9., 10.,  4.],
        [11., 10., 11.,  9.]]])

In [17]:
valoraciones_2.mean()

6.458333333333333

In [26]:
# Convertir una lista en un array
np.reshape([i for i in range(1, 37)], (3, 3, 4))

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]]])